/**
 * Seed script: Populates the Course collection with real government-backed courses.
 * Sources: NPTEL, SWAYAM, Skill India Digital Hub
 *
 * Run: npx ts-node scripts/seed_courses.ts
 */

import mongoose from 'mongoose';
import dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.join(__dirname, '../.env') });

import Course from '../src/models/Course';
import { generateEmbedding } from '../src/services/gemini.service';

const COURSES = [
    // ===== NPTEL Courses =====
    {
        title: 'The Joy of Computing using Python',
        provider: 'NPTEL' as const,
        url: 'https://nptel.ac.in/courses/106106182',
        skills: ['Python', 'Programming', 'Computational Thinking'],
        duration: '12 weeks',
        level: 'Beginner' as const,
        language: 'English',
        institution: 'IIT Ropar',
        description: 'Learn Python programming through fun examples and computational thinking. Covers basics, data structures, algorithms, and real-world applications.',
    },
    {
        title: 'Programming, Data Structures and Algorithms using Python',
        provider: 'NPTEL' as const,
        url: 'https://nptel.ac.in/courses/106106145',
        skills: ['Python', 'Data Structures', 'Algorithms', 'Programming'],
        duration: '8 weeks',
        level: 'Intermediate' as const,
        language: 'English',
        institution: 'IIT Madras',
        description: 'Covers sorting, searching, graph algorithms, and data structures like stacks, queues, trees, and hash tables using Python.',
    },
    {
        title: 'Introduction to Machine Learning',
        provider: 'NPTEL' as const,
        url: 'https://nptel.ac.in/courses/106106139',
        skills: ['Machine Learning', 'AI', 'Python', 'Data Science', 'Statistics'],
        duration: '12 weeks',
        level: 'Intermediate' as const,
        language: 'English',
        institution: 'IIT Kharagpur',
        description: 'Comprehensive introduction to machine learning covering supervised and unsupervised learning, neural networks, SVMs, decision trees, and ensemble methods.',
    },
    {
        title: 'Deep Learning',
        provider: 'NPTEL' as const,
        url: 'https://nptel.ac.in/courses/106106184',
        skills: ['Deep Learning', 'Neural Networks', 'AI', 'TensorFlow', 'Python'],
        duration: '12 weeks',
        level: 'Advanced' as const,
        language: 'English',
        institution: 'IIT Madras',
        description: 'Covers feedforward networks, CNNs, RNNs, attention mechanisms, transformers, GANs, and practical deep learning with TensorFlow.',
    },
    {
        title: 'Database Management System',
        provider: 'NPTEL' as const,
        url: 'https://nptel.ac.in/courses/106105175',
        skills: ['SQL', 'Database', 'DBMS', 'Relational Database', 'Data Modeling'],
        duration: '12 weeks',
        level: 'Intermediate' as const,
        language: 'English',
        institution: 'IIT Kharagpur',
        description: 'Covers relational model, SQL, normalization, transaction management, concurrency control, and query optimization.',
    },
    {
        title: 'Cloud Computing',
        provider: 'NPTEL' as const,
        url: 'https://nptel.ac.in/courses/106105167',
        skills: ['Cloud Computing', 'AWS', 'Virtualization', 'DevOps', 'Distributed Systems'],
        duration: '8 weeks',
        level: 'Intermediate' as const,
        language: 'English',
        institution: 'IIT Kharagpur',
        description: 'Introduction to cloud computing paradigms, virtualization, cloud architecture, service models (IaaS, PaaS, SaaS), and cloud security.',
    },
    {
        title: 'Computer Networks and Internet Protocol',
        provider: 'NPTEL' as const,
        url: 'https://nptel.ac.in/courses/106105183',
        skills: ['Computer Networks', 'Networking', 'TCP/IP', 'HTTP', 'Security'],
        duration: '8 weeks',
        level: 'Intermediate' as const,
        language: 'English',
        institution: 'IIT Kharagpur',
        description: 'Covers OSI model, TCP/IP, routing, DNS, HTTP, network security, and internet protocols.',
    },
    {
        title: 'Data Science for Engineers',
        provider: 'NPTEL' as const,
        url: 'https://nptel.ac.in/courses/106106179',
        skills: ['Data Science', 'Statistics', 'Python', 'Data Analysis', 'Visualization'],
        duration: '8 weeks',
        level: 'Beginner' as const,
        language: 'English',
        institution: 'IIT Madras',
        description: 'Introduction to data science covering statistics, probability, data wrangling, visualization, and basic machine learning for engineering students.',
    },
    {
        title: 'Introduction to Internet of Things',
        provider: 'NPTEL' as const,
        url: 'https://nptel.ac.in/courses/106105166',
        skills: ['IoT', 'Embedded Systems', 'Sensors', 'Arduino', 'Raspberry Pi'],
        duration: '12 weeks',
        level: 'Beginner' as const,
        language: 'English',
        institution: 'IIT Kharagpur',
        description: 'Covers IoT architecture, sensors, communication protocols, embedded platforms (Arduino, Raspberry Pi), and IoT applications.',
    },
    {
        title: 'Cyber Security and Privacy',
        provider: 'NPTEL' as const,
        url: 'https://nptel.ac.in/courses/106106178',
        skills: ['Cybersecurity', 'Network Security', 'Cryptography', 'Information Security'],
        duration: '12 weeks',
        level: 'Intermediate' as const,
        language: 'English',
        institution: 'IIT Madras',
        description: 'Covers network security, cryptographic protocols, web security, malware analysis, and privacy-preserving techniques.',
    },
    {
        title: 'Software Engineering',
        provider: 'NPTEL' as const,
        url: 'https://nptel.ac.in/courses/106105182',
        skills: ['Software Engineering', 'SDLC', 'Testing', 'Agile', 'Project Management'],
        duration: '8 weeks',
        level: 'Intermediate' as const,
        language: 'English',
        institution: 'IIT Kharagpur',
        description: 'Covers software development lifecycle, requirements engineering, design patterns, testing strategies, agile methodologies, and project management.',
    },
    {
        title: 'Problem Solving through Programming in C',
        provider: 'NPTEL' as const,
        url: 'https://nptel.ac.in/courses/106105171',
        skills: ['C Programming', 'Programming', 'Problem Solving', 'Algorithms'],
        duration: '8 weeks',
        level: 'Beginner' as const,
        language: 'English',
        institution: 'IIT Kharagpur',
        description: 'Learn fundamentals of C programming including variables, control flow, functions, arrays, pointers, and file handling through problem solving.',
    },

    // ===== SWAYAM Courses =====
    {
        title: 'Communication Skills',
        provider: 'SWAYAM' as const,
        url: 'https://swayam.gov.in/nd1_noc20_hs61',
        skills: ['Communication Skills', 'English Communication', 'Soft Skills', 'Presentation'],
        duration: '8 weeks',
        level: 'Beginner' as const,
        language: 'English',
        institution: 'IIT Kanpur',
        description: 'Develop effective communication skills including speaking, writing, listening, and presentation techniques for professional settings.',
    },
    {
        title: 'Soft Skills',
        provider: 'SWAYAM' as const,
        url: 'https://swayam.gov.in/nd1_noc20_hs57',
        skills: ['Soft Skills', 'Teamwork', 'Leadership', 'Time Management', 'Communication Skills'],
        duration: '8 weeks',
        level: 'Beginner' as const,
        language: 'English',
        institution: 'IIT Kanpur',
        description: 'Comprehensive course covering teamwork, leadership, conflict resolution, emotional intelligence, and time management for career readiness.',
    },
    {
        title: 'Effective Business Communication',
        provider: 'SWAYAM' as const,
        url: 'https://swayam.gov.in/nd1_noc20_mg53',
        skills: ['Business Communication', 'Writing Skills', 'Email Writing', 'Communication Skills'],
        duration: '4 weeks',
        level: 'Beginner' as const,
        language: 'English',
        institution: 'IIM Bangalore',
        description: 'Learn professional business communication including email writing, report writing, meeting management, and cross-cultural communication.',
    },
    {
        title: 'Introduction to Web Development',
        provider: 'SWAYAM' as const,
        url: 'https://swayam.gov.in/nd2_cec20_cs13',
        skills: ['HTML', 'CSS', 'JavaScript', 'Web Development', 'Frontend'],
        duration: '8 weeks',
        level: 'Beginner' as const,
        language: 'English',
        institution: 'CEC',
        description: 'Learn web development fundamentals including HTML5, CSS3, JavaScript, responsive design, and basic web application development.',
    },
    {
        title: 'Programming in Java',
        provider: 'SWAYAM' as const,
        url: 'https://swayam.gov.in/nd1_noc20_cs08',
        skills: ['Java', 'OOP', 'Programming', 'Data Structures'],
        duration: '12 weeks',
        level: 'Beginner' as const,
        language: 'English',
        institution: 'IIT Kharagpur',
        description: 'Complete Java programming course covering OOP concepts, inheritance, polymorphism, exception handling, collections, and multithreading.',
    },
    {
        title: 'Data Analytics with Python',
        provider: 'SWAYAM' as const,
        url: 'https://swayam.gov.in/nd1_noc20_cs32',
        skills: ['Data Analytics', 'Python', 'Pandas', 'NumPy', 'Data Visualization', 'Data Science'],
        duration: '8 weeks',
        level: 'Intermediate' as const,
        language: 'English',
        institution: 'IIT Roorkee',
        description: 'Learn data analytics using Python with Pandas, NumPy, Matplotlib, and Seaborn. Covers data cleaning, exploration, and visualization.',
    },
    {
        title: 'Artificial Intelligence: Search Methods for Problem Solving',
        provider: 'SWAYAM' as const,
        url: 'https://swayam.gov.in/nd1_noc20_cs35',
        skills: ['AI', 'Artificial Intelligence', 'Search Algorithms', 'Problem Solving'],
        duration: '12 weeks',
        level: 'Intermediate' as const,
        language: 'English',
        institution: 'IIT Madras',
        description: 'Covers AI search methods including BFS, DFS, A*, minimax, constraint satisfaction, and heuristic-based problem solving approaches.',
    },

    // ===== Skill India Digital Hub =====
    {
        title: 'Python Programming',
        provider: 'SkillIndia' as const,
        url: 'https://skillindiadigital.gov.in/courses/python-programming',
        skills: ['Python', 'Programming', 'Software Development'],
        duration: 'Self-paced',
        level: 'Beginner' as const,
        language: 'English',
        institution: 'Skill India',
        description: 'Government-backed free Python programming course covering fundamentals, OOP, file handling, and practical coding exercises.',
    },
    {
        title: 'Cybersecurity Fundamentals',
        provider: 'SkillIndia' as const,
        url: 'https://skillindiadigital.gov.in/courses/cybersecurity',
        skills: ['Cybersecurity', 'Network Security', 'Information Security', 'Ethical Hacking'],
        duration: 'Self-paced',
        level: 'Beginner' as const,
        language: 'English',
        institution: 'Skill India',
        description: 'Learn cybersecurity fundamentals including threat detection, network security, encryption, and ethical hacking basics.',
    },
    {
        title: 'Digital Marketing',
        provider: 'SkillIndia' as const,
        url: 'https://skillindiadigital.gov.in/courses/digital-marketing',
        skills: ['Digital Marketing', 'SEO', 'Social Media Marketing', 'Content Marketing'],
        duration: 'Self-paced',
        level: 'Beginner' as const,
        language: 'English',
        institution: 'Skill India',
        description: 'Learn digital marketing including SEO, social media marketing, email marketing, Google Ads, and content strategy.',
    },
    {
        title: 'Data Entry and Office Automation',
        provider: 'SkillIndia' as const,
        url: 'https://skillindiadigital.gov.in/courses/data-entry',
        skills: ['Data Entry', 'MS Office', 'Excel', 'Office Automation', 'Typing'],
        duration: 'Self-paced',
        level: 'Beginner' as const,
        language: 'Hindi',
        institution: 'Skill India',
        description: 'Government course on data entry operations, MS Office (Word, Excel, PowerPoint), and office automation tools. Available in Hindi.',
    },
    {
        title: 'Tally with GST',
        provider: 'SkillIndia' as const,
        url: 'https://skillindiadigital.gov.in/courses/tally-gst',
        skills: ['Tally', 'Accounting', 'GST', 'Finance', 'Bookkeeping'],
        duration: 'Self-paced',
        level: 'Beginner' as const,
        language: 'English',
        institution: 'Skill India',
        description: 'Learn accounting with Tally software including GST filing, voucher entry, balance sheets, and financial reporting.',
    },
    {
        title: 'Spoken English',
        provider: 'SkillIndia' as const,
        url: 'https://skillindiadigital.gov.in/courses/spoken-english',
        skills: ['English', 'Communication Skills', 'Spoken English', 'Language'],
        duration: 'Self-paced',
        level: 'Beginner' as const,
        language: 'Hindi',
        institution: 'Skill India',
        description: 'Improve spoken English skills with practical exercises, conversation practice, and vocabulary building. Taught in Hindi for accessibility.',
    },

    // ===== eSkill India / NSDC =====
    {
        title: 'Web Designing using HTML & CSS',
        provider: 'eSkillIndia' as const,
        url: 'https://eskillindia.org/Home/course_detail/436',
        skills: ['HTML', 'CSS', 'Web Design', 'Frontend', 'Web Development'],
        duration: '40 hours',
        level: 'Beginner' as const,
        language: 'English',
        institution: 'NSDC',
        description: 'Learn web designing fundamentals using HTML5 and CSS3 with practical projects, responsive design, and deployment.',
    },
    {
        title: 'Android App Development',
        provider: 'eSkillIndia' as const,
        url: 'https://eskillindia.org/Home/course_detail/android',
        skills: ['Android', 'Mobile Development', 'Java', 'Kotlin', 'App Development'],
        duration: '60 hours',
        level: 'Intermediate' as const,
        language: 'English',
        institution: 'NSDC',
        description: 'Build Android applications using Java/Kotlin, Android Studio, UI design, APIs, and Google Play Store publishing.',
    },
    {
        title: 'React JS for Beginners',
        provider: 'eSkillIndia' as const,
        url: 'https://eskillindia.org/Home/course_detail/reactjs',
        skills: ['React', 'JavaScript', 'Frontend', 'Web Development', 'Node.js'],
        duration: '40 hours',
        level: 'Beginner' as const,
        language: 'English',
        institution: 'NSDC',
        description: 'Learn React.js from scratch including components, hooks, state management, routing, and building single-page applications.',
    },
    {
        title: 'Advanced Excel and Data Analysis',
        provider: 'eSkillIndia' as const,
        url: 'https://eskillindia.org/Home/course_detail/excel',
        skills: ['Excel', 'Data Analysis', 'VBA', 'Pivot Tables', 'Data Visualization'],
        duration: '30 hours',
        level: 'Intermediate' as const,
        language: 'English',
        institution: 'NSDC',
        description: 'Master advanced Excel features including pivot tables, VLOOKUP, macros, VBA, data analysis tools, and dashboard creation.',
    },
    {
        title: 'Full Stack Development with Node.js',
        provider: 'eSkillIndia' as const,
        url: 'https://eskillindia.org/Home/course_detail/fullstack',
        skills: ['Node.js', 'Express', 'MongoDB', 'JavaScript', 'Full Stack', 'REST API'],
        duration: '80 hours',
        level: 'Intermediate' as const,
        language: 'English',
        institution: 'NSDC',
        description: 'Build full-stack web applications using Node.js, Express, MongoDB, and React. Covers REST APIs, authentication, and deployment.',
    },
    {
        title: 'AWS Cloud Practitioner Essentials',
        provider: 'eSkillIndia' as const,
        url: 'https://eskillindia.org/Home/course_detail/aws',
        skills: ['AWS', 'Cloud Computing', 'DevOps', 'Cloud Architecture'],
        duration: '40 hours',
        level: 'Beginner' as const,
        language: 'English',
        institution: 'NSDC',
        description: 'Introduction to AWS cloud services covering EC2, S3, Lambda, RDS, IAM, and cloud architecture best practices.',
    },

    // ===== FINANCE & ACCOUNTING =====
    {
        title: 'Financial Accounting',
        provider: 'NPTEL' as const,
        url: 'https://nptel.ac.in/courses/110105035',
        skills: ['Financial Accounting', 'Accounting', 'Balance Sheet', 'Journal Entries', 'Finance'],
        duration: '12 weeks',
        level: 'Beginner' as const,
        language: 'English',
        institution: 'IIT Kharagpur',
        description: 'Covers fundamentals of financial accounting including double-entry bookkeeping, journal entries, ledger, trial balance, and financial statement preparation.',
    },
    {
        title: 'Financial Management',
        provider: 'SWAYAM' as const,
        url: 'https://swayam.gov.in/nd1_noc20_mg32',
        skills: ['Financial Management', 'Finance', 'Investment', 'Capital Budgeting', 'Risk Management'],
        duration: '12 weeks',
        level: 'Intermediate' as const,
        language: 'English',
        institution: 'IIM Bangalore',
        description: 'Covers time value of money, capital budgeting, cost of capital, capital structure, dividend policy, and working capital management.',
    },
    {
        title: 'Securities Market Operations',
        provider: 'NPTEL' as const,
        url: 'https://nptel.ac.in/courses/110105147',
        skills: ['Stock Market', 'Securities', 'Trading', 'Finance', 'Investment', 'Capital Markets'],
        duration: '8 weeks',
        level: 'Intermediate' as const,
        language: 'English',
        institution: 'IIT Kharagpur',
        description: 'Learn about Indian securities markets, stock exchanges, trading mechanisms, derivatives, mutual funds, and SEBI regulations.',
    },
    {
        title: 'Banking and Financial Services',
        provider: 'SWAYAM' as const,
        url: 'https://swayam.gov.in/nd1_noc20_mg40',
        skills: ['Banking', 'Financial Services', 'Loans', 'Credit', 'Finance', 'Insurance'],
        duration: '8 weeks',
        level: 'Beginner' as const,
        language: 'English',
        institution: 'IIM Tiruchirappalli',
        description: 'Overview of banking system, types of banks, credit facilities, insurance, mutual funds, and fintech innovations in India.',
    },
    {
        title: 'Goods and Services Tax (GST)',
        provider: 'SkillIndia' as const,
        url: 'https://skillindiadigital.gov.in/courses/gst',
        skills: ['GST', 'Taxation', 'Tax Filing', 'Finance', 'Accounting', 'Compliance'],
        duration: 'Self-paced',
        level: 'Beginner' as const,
        language: 'Hindi',
        institution: 'Skill India',
        description: 'Complete guide to GST including registration, invoicing, GSTR filing, input tax credit, and compliance requirements for businesses.',
    },
    {
        title: 'Income Tax Return Filing',
        provider: 'SkillIndia' as const,
        url: 'https://skillindiadigital.gov.in/courses/income-tax',
        skills: ['Income Tax', 'Tax Filing', 'ITR', 'Finance', 'Tax Planning'],
        duration: 'Self-paced',
        level: 'Beginner' as const,
        language: 'Hindi',
        institution: 'Skill India',
        description: 'Learn income tax fundamentals, tax slabs, deductions under 80C/80D, ITR filing process, and tax planning strategies for individuals.',
    },
    {
        title: 'Financial Markets and Institutions',
        provider: 'NPTEL' as const,
        url: 'https://nptel.ac.in/courses/110105033',
        skills: ['Financial Markets', 'Banking', 'Capital Markets', 'Finance', 'Economics'],
        duration: '12 weeks',
        level: 'Intermediate' as const,
        language: 'English',
        institution: 'IIT Kanpur',
        description: 'Study of financial markets including money markets, bond markets, equity markets, derivatives markets, and the role of financial institutions.',
    },

    // ===== MANAGEMENT & BUSINESS =====
    {
        title: 'Principles of Management',
        provider: 'NPTEL' as const,
        url: 'https://nptel.ac.in/courses/110105034',
        skills: ['Management', 'Leadership', 'Planning', 'Organization', 'Business'],
        duration: '12 weeks',
        level: 'Beginner' as const,
        language: 'English',
        institution: 'IIT Kharagpur',
        description: 'Covers planning, organizing, staffing, directing, and controlling. Includes organizational behavior, motivation theories, and decision making.',
    },
    {
        title: 'Marketing Management',
        provider: 'SWAYAM' as const,
        url: 'https://swayam.gov.in/nd1_noc20_mg07',
        skills: ['Marketing', 'Brand Management', 'Consumer Behavior', 'Market Research', 'Sales'],
        duration: '12 weeks',
        level: 'Beginner' as const,
        language: 'English',
        institution: 'IIM Bangalore',
        description: 'Covers marketing mix, segmentation, targeting, positioning, consumer behavior, brand management, pricing, and distribution strategies.',
    },
    {
        title: 'Human Resource Management',
        provider: 'SWAYAM' as const,
        url: 'https://swayam.gov.in/nd1_noc20_mg18',
        skills: ['HR Management', 'Recruitment', 'Performance Management', 'Training', 'Labor Law'],
        duration: '8 weeks',
        level: 'Beginner' as const,
        language: 'English',
        institution: 'IIM Ranchi',
        description: 'Covers recruitment, selection, training, performance appraisal, compensation, employee relations, and HR analytics.',
    },
    {
        title: 'Entrepreneurship',
        provider: 'NPTEL' as const,
        url: 'https://nptel.ac.in/courses/110105141',
        skills: ['Entrepreneurship', 'Startup', 'Business Plan', 'Innovation', 'Business'],
        duration: '12 weeks',
        level: 'Beginner' as const,
        language: 'English',
        institution: 'IIT Kharagpur',
        description: 'Covers entrepreneurial mindset, opportunity identification, business model canvas, funding, legal aspects, and scaling startups in India.',
    },
    {
        title: 'Supply Chain Management',
        provider: 'NPTEL' as const,
        url: 'https://nptel.ac.in/courses/110105142',
        skills: ['Supply Chain', 'Logistics', 'Inventory Management', 'Operations', 'Procurement'],
        duration: '8 weeks',
        level: 'Intermediate' as const,
        language: 'English',
        institution: 'IIT Bombay',
        description: 'Covers supply chain design, procurement, inventory management, logistics, warehousing, demand forecasting, and supply chain analytics.',
    },
    {
        title: 'Project Management',
        provider: 'SWAYAM' as const,
        url: 'https://swayam.gov.in/nd1_noc20_mg24',
        skills: ['Project Management', 'Agile', 'PMP', 'Planning', 'Risk Management'],
        duration: '8 weeks',
        level: 'Intermediate' as const,
        language: 'English',
        institution: 'IIT Delhi',
        description: 'Covers project lifecycle, scope, scheduling (PERT/CPM), cost estimation, risk management, quality assurance, and agile methodologies.',
    },

    // ===== HEALTHCARE & LIFE SCIENCES =====
    {
        title: 'Introduction to Biomedical Engineering',
        provider: 'NPTEL' as const,
        url: 'https://nptel.ac.in/courses/108105088',
        skills: ['Biomedical Engineering', 'Healthcare', 'Medical Devices', 'Biology'],
        duration: '12 weeks',
        level: 'Beginner' as const,
        language: 'English',
        institution: 'IIT Madras',
        description: 'Introduction to biomedical engineering covering biomechanics, biomaterials, medical imaging, biosensors, and medical device design.',
    },
    {
        title: 'Health Research Fundamentals',
        provider: 'SWAYAM' as const,
        url: 'https://swayam.gov.in/nd2_ugc20_hs11',
        skills: ['Health Research', 'Public Health', 'Epidemiology', 'Healthcare', 'Research Methods'],
        duration: '8 weeks',
        level: 'Beginner' as const,
        language: 'English',
        institution: 'UGC',
        description: 'Covers health research methods, epidemiology, biostatistics, clinical trials, public health surveys, and research ethics.',
    },
    {
        title: 'Community Health Nursing',
        provider: 'SkillIndia' as const,
        url: 'https://skillindiadigital.gov.in/courses/community-health',
        skills: ['Nursing', 'Community Health', 'Healthcare', 'Patient Care', 'Public Health'],
        duration: 'Self-paced',
        level: 'Beginner' as const,
        language: 'Hindi',
        institution: 'Skill India',
        description: 'Community health nursing fundamentals including patient assessment, primary healthcare, maternal health, immunization, and health education.',
    },
    {
        title: 'Pharmacy Practice',
        provider: 'SWAYAM' as const,
        url: 'https://swayam.gov.in/nd2_ugc20_ph01',
        skills: ['Pharmacy', 'Pharmaceutical', 'Drug Administration', 'Healthcare', 'Clinical Pharmacy'],
        duration: '8 weeks',
        level: 'Intermediate' as const,
        language: 'English',
        institution: 'UGC',
        description: 'Covers pharmacy practice, drug interactions, patient counseling, prescription analysis, clinical pharmacy, and pharmacovigilance.',
    },

    // ===== LAW & GOVERNANCE =====
    {
        title: 'Introduction to Indian Contract Law',
        provider: 'SWAYAM' as const,
        url: 'https://swayam.gov.in/nd2_ugc20_lw02',
        skills: ['Contract Law', 'Law', 'Legal', 'Indian Law', 'Business Law'],
        duration: '8 weeks',
        level: 'Beginner' as const,
        language: 'English',
        institution: 'UGC',
        description: 'Covers Indian Contract Act, offer and acceptance, consideration, capacity, free consent, void agreements, breach of contract, and remedies.',
    },
    {
        title: 'Intellectual Property Rights',
        provider: 'NPTEL' as const,
        url: 'https://nptel.ac.in/courses/110105139',
        skills: ['IPR', 'Patent', 'Copyright', 'Trademark', 'Law', 'Legal'],
        duration: '8 weeks',
        level: 'Beginner' as const,
        language: 'English',
        institution: 'IIT Kharagpur',
        description: 'Covers patents, copyrights, trademarks, trade secrets, geographical indications, and IPR enforcement in Indian and international contexts.',
    },
    {
        title: 'Cyber Law',
        provider: 'SWAYAM' as const,
        url: 'https://swayam.gov.in/nd2_ugc20_lw06',
        skills: ['Cyber Law', 'IT Act', 'Data Privacy', 'Law', 'Legal', 'Information Technology'],
        duration: '8 weeks',
        level: 'Beginner' as const,
        language: 'English',
        institution: 'UGC',
        description: 'Covers IT Act 2000, data protection, digital signatures, cyber crimes, e-commerce regulations, and social media legal issues in India.',
    },

    // ===== AGRICULTURE =====
    {
        title: 'Precision Farming',
        provider: 'NPTEL' as const,
        url: 'https://nptel.ac.in/courses/126105015',
        skills: ['Agriculture', 'Farming', 'Precision Agriculture', 'Crop Management', 'Agritech'],
        duration: '8 weeks',
        level: 'Intermediate' as const,
        language: 'English',
        institution: 'IIT Kharagpur',
        description: 'Covers GPS-guided farming, remote sensing, GIS in agriculture, soil analysis, crop monitoring, and smart irrigation techniques.',
    },
    {
        title: 'Organic Farming',
        provider: 'SkillIndia' as const,
        url: 'https://skillindiadigital.gov.in/courses/organic-farming',
        skills: ['Organic Farming', 'Agriculture', 'Composting', 'Soil Management', 'Farming'],
        duration: 'Self-paced',
        level: 'Beginner' as const,
        language: 'Hindi',
        institution: 'Skill India',
        description: 'Learn organic farming techniques including composting, vermicomposting, bio-pesticides, crop rotation, and organic certification process.',
    },
    {
        title: 'Food Processing and Preservation',
        provider: 'SWAYAM' as const,
        url: 'https://swayam.gov.in/nd1_noc20_ag02',
        skills: ['Food Processing', 'Food Technology', 'Preservation', 'Agriculture', 'Quality Control'],
        duration: '8 weeks',
        level: 'Beginner' as const,
        language: 'English',
        institution: 'IIT Kharagpur',
        description: 'Covers food processing methods, drying, canning, freezing, fermentation, food packaging, FSSAI regulations, and quality assurance.',
    },

    // ===== DESIGN & CREATIVE =====
    {
        title: 'Introduction to Graphic Design',
        provider: 'eSkillIndia' as const,
        url: 'https://eskillindia.org/Home/course_detail/graphic-design',
        skills: ['Graphic Design', 'Photoshop', 'Illustrator', 'Design', 'UI Design', 'Visual Design'],
        duration: '40 hours',
        level: 'Beginner' as const,
        language: 'English',
        institution: 'NSDC',
        description: 'Learn graphic design principles, color theory, typography, Adobe Photoshop, Illustrator, and creating logos, posters, and social media graphics.',
    },
    {
        title: 'UI/UX Design Fundamentals',
        provider: 'eSkillIndia' as const,
        url: 'https://eskillindia.org/Home/course_detail/uiux',
        skills: ['UI Design', 'UX Design', 'Wireframing', 'Prototyping', 'Figma', 'Design'],
        duration: '50 hours',
        level: 'Beginner' as const,
        language: 'English',
        institution: 'NSDC',
        description: 'Learn UX research, user personas, wireframing, prototyping with Figma, usability testing, and responsive design principles.',
    },
    {
        title: 'Photography and Videography',
        provider: 'SkillIndia' as const,
        url: 'https://skillindiadigital.gov.in/courses/photography',
        skills: ['Photography', 'Videography', 'Video Editing', 'Creative', 'Content Creation'],
        duration: 'Self-paced',
        level: 'Beginner' as const,
        language: 'Hindi',
        institution: 'Skill India',
        description: 'Learn photography composition, lighting, camera settings, video shooting techniques, and basic video editing for content creation.',
    },

    // ===== CIVIL & MECHANICAL ENGINEERING =====
    {
        title: 'Strength of Materials',
        provider: 'NPTEL' as const,
        url: 'https://nptel.ac.in/courses/112105171',
        skills: ['Strength of Materials', 'Mechanical Engineering', 'Stress Analysis', 'Structural Engineering'],
        duration: '12 weeks',
        level: 'Intermediate' as const,
        language: 'English',
        institution: 'IIT Madras',
        description: 'Covers stress, strain, Mohr circle, bending, shear force diagrams, torsion, deflection of beams, and columns.',
    },
    {
        title: 'Building Construction and Materials',
        provider: 'SWAYAM' as const,
        url: 'https://swayam.gov.in/nd1_noc20_ce05',
        skills: ['Civil Engineering', 'Construction', 'Building Materials', 'Structural Design'],
        duration: '8 weeks',
        level: 'Beginner' as const,
        language: 'English',
        institution: 'IIT Roorkee',
        description: 'Covers building materials (cement, steel, bricks), foundation types, wall construction, roofing, flooring, and green building concepts.',
    },
    {
        title: 'Electrical Wiring and Installation',
        provider: 'SkillIndia' as const,
        url: 'https://skillindiadigital.gov.in/courses/electrical-wiring',
        skills: ['Electrical', 'Wiring', 'Installation', 'Electrician', 'Electrical Engineering'],
        duration: 'Self-paced',
        level: 'Beginner' as const,
        language: 'Hindi',
        institution: 'Skill India',
        description: 'Covers domestic electrical wiring, earthing, circuit breakers, electrical safety, meter installation, and basic motor winding.',
    },

    // ===== ECONOMICS & SOCIAL SCIENCES =====
    {
        title: 'Microeconomics',
        provider: 'NPTEL' as const,
        url: 'https://nptel.ac.in/courses/109105104',
        skills: ['Microeconomics', 'Economics', 'Market Analysis', 'Demand Supply', 'Price Theory'],
        duration: '12 weeks',
        level: 'Beginner' as const,
        language: 'English',
        institution: 'IIT Kanpur',
        description: 'Covers demand-supply analysis, consumer theory, production theory, market structures, game theory, and welfare economics.',
    },
    {
        title: 'Indian Economy',
        provider: 'SWAYAM' as const,
        url: 'https://swayam.gov.in/nd2_ugc20_ec03',
        skills: ['Indian Economy', 'Economics', 'GDP', 'Economic Policy', 'Development Economics'],
        duration: '8 weeks',
        level: 'Beginner' as const,
        language: 'English',
        institution: 'UGC',
        description: 'Covers Indian economic structure, five-year plans, agricultural sector, industrial policy, foreign trade, banking, and economic reforms.',
    },
    {
        title: 'Environmental Studies',
        provider: 'SWAYAM' as const,
        url: 'https://swayam.gov.in/nd2_ugc20_ev01',
        skills: ['Environmental Science', 'Sustainability', 'Ecology', 'Pollution Control', 'Climate Change'],
        duration: '8 weeks',
        level: 'Beginner' as const,
        language: 'English',
        institution: 'UGC',
        description: 'Covers ecosystems, biodiversity, pollution, waste management, environmental laws, climate change, and sustainable development goals.',
    },

    // ===== LANGUAGE & TEACHING =====
    {
        title: 'Teaching and Learning in Higher Education',
        provider: 'SWAYAM' as const,
        url: 'https://swayam.gov.in/nd2_ugc20_ed01',
        skills: ['Teaching', 'Education', 'Pedagogy', 'Curriculum Design', 'Assessment'],
        duration: '8 weeks',
        level: 'Beginner' as const,
        language: 'English',
        institution: 'UGC',
        description: 'Covers teaching methods, lesson planning, curriculum design, classroom management, assessment strategies, and educational technology.',
    },
    {
        title: 'Technical Writing',
        provider: 'NPTEL' as const,
        url: 'https://nptel.ac.in/courses/109106120',
        skills: ['Technical Writing', 'Documentation', 'Writing Skills', 'Report Writing', 'Communication Skills'],
        duration: '8 weeks',
        level: 'Beginner' as const,
        language: 'English',
        institution: 'IIT Madras',
        description: 'Learn technical writing skills including reports, proposals, research papers, user manuals, SOPs, and professional email communication.',
    },

    // ===== HOSPITALITY & TOURISM =====
    {
        title: 'Hotel Management and Tourism',
        provider: 'SkillIndia' as const,
        url: 'https://skillindiadigital.gov.in/courses/hotel-management',
        skills: ['Hotel Management', 'Tourism', 'Hospitality', 'Front Office', 'Customer Service'],
        duration: 'Self-paced',
        level: 'Beginner' as const,
        language: 'Hindi',
        institution: 'Skill India',
        description: 'Covers front office management, housekeeping, food and beverage service, tourism geography, customer handling, and hospitality communication.',
    },
    {
        title: 'Beauty and Wellness',
        provider: 'SkillIndia' as const,
        url: 'https://skillindiadigital.gov.in/courses/beauty-wellness',
        skills: ['Beauty', 'Wellness', 'Cosmetology', 'Salon Management', 'Personal Grooming'],
        duration: 'Self-paced',
        level: 'Beginner' as const,
        language: 'Hindi',
        institution: 'Skill India',
        description: 'Learn beauty therapy, hair styling, skin care, nail art, salon management, and personal grooming techniques for professional cosmetology.',
    },

    // ===== DATA & ANALYTICS (non-tech roles) =====
    {
        title: 'Business Analytics',
        provider: 'NPTEL' as const,
        url: 'https://nptel.ac.in/courses/110105092',
        skills: ['Business Analytics', 'Data Analysis', 'Statistics', 'Decision Making', 'Excel'],
        duration: '12 weeks',
        level: 'Intermediate' as const,
        language: 'English',
        institution: 'IIT Kharagpur',
        description: 'Covers descriptive analytics, predictive modeling, optimization, regression analysis, hypothesis testing, and data-driven business decisions.',
    },
    {
        title: 'Statistics for Data Science',
        provider: 'SWAYAM' as const,
        url: 'https://swayam.gov.in/nd1_noc20_ma04',
        skills: ['Statistics', 'Probability', 'Data Science', 'Hypothesis Testing', 'Regression'],
        duration: '8 weeks',
        level: 'Beginner' as const,
        language: 'English',
        institution: 'IIT Kanpur',
        description: 'Covers probability theory, distributions, estimation, hypothesis testing, ANOVA, regression, and correlation for data science applications.',
    },
];

async function seed() {
    const mongoUri = process.env.MONGODB_URI || process.env.MONGO_URI;
    if (!mongoUri) {
        console.error('MONGODB_URI not set in .env');
        process.exit(1);
    }

    await mongoose.connect(mongoUri);
    console.log('Connected to MongoDB');

    // Clear existing courses
    await Course.deleteMany({});
    console.log('Cleared existing courses');

    let seeded = 0;
    for (const course of COURSES) {
        const skillsText = `${course.title} ${course.skills.join(' ')} ${course.description}`;
        const embedding = await generateEmbedding(skillsText);

        await Course.create({
            ...course,
            skillsText,
            skillsEmbedding: embedding || undefined,
            isFree: true,
            active: true,
        });

        seeded++;
        console.log(`[${seeded}/${COURSES.length}] Seeded: ${course.title} (${course.provider})`);
    }

    console.log(`\nDone! Seeded ${seeded} courses.`);
    await mongoose.disconnect();
    process.exit(0);
}

seed().catch((err) => {
    console.error('Seed failed:', err);
    process.exit(1);
});
